Revert "dyff try 4"
This reverts commit 5eca334673bdc6d1a840a52c669b71635acb905f.

diff --git a/.github/workflows/diff-preview.yaml b/.github/workflows/diff-preview.yaml
--- a/.github/workflows/diff-preview.yaml
+++ b/.github/workflows/diff-preview.yaml
@@ -37,7 +37,7 @@ jobs:
         uses: mathiasvr/command-output@v1
         id: diff
         with:
-          run: 'dyff between -s -i -b -g -c on /tmp/old.yaml /tmp/new.yaml && echo "No diff detected" || if [[ $? -eq 255 ]]; then echo "Diff error"; fi;'
+          run: 'dyff between -s -i -b -g /tmp/old.yaml /tmp/new.yaml && echo "No diff detected" || if [[ $? -eq 255 ]]; then echo "Diff error"; fi;'
       - name: Find diff comment
         uses: peter-evans/find-comment@v2
         id: fc
