better msg

diff --git a/.github/workflows/diff-preview.yaml b/.github/workflows/diff-preview.yaml
--- a/.github/workflows/diff-preview.yaml
+++ b/.github/workflows/diff-preview.yaml
@@ -30,21 +30,21 @@ jobs:
         uses: mathiasvr/command-output@v1
         id: diff
         with:
-          run: "diff /tmp/old.yaml /tmp/new.yaml || true"
+          run: "diff /tmp/old.yaml /tmp/new.yaml && echo "No diffi detected" || if [[ $? -eq 2 ]]; then echo "Diff error"; fi;
       - name: Find diff comment
         uses: peter-evans/find-comment@v2
         id: fc
         with:
           issue-number: ${{ github.event.pull_request.number }}
           comment-author: 'github-actions[bot]'
-          body-includes: Diff output log
+          body-includes: Rendered manifest diff output log
       - name: Create or update validation comment
         uses: peter-evans/create-or-update-comment@v2
         with:
           comment-id: ${{ steps.fc.outputs.comment-id }}
           issue-number: ${{ github.event.pull_request.number }}
           body: |
-            Diff output log
+            Rendered manifest diff output log
 
             ```diff
             ${{ steps.diff.outputs.stdout }}
